# 应用服务 WEB 访问端口
server:
    port: 9090

spring:
    datasource:
        #数据库连接驱动类
        driver-class-name: com.mysql.cj.jdbc.Driver
        #配置链接数据库url，serverTimezone=GMT%2b8【时区：北京时间】
        url: jdbc:mysql://localhost:3306/demo12?serverTimezone=GMT%2b8
        username: root
        password: root

#指定Mybatis的Mapper文件
mybatis:
    mapper-locations: classpath:mapper/*.xml
    #指定Mybatis的实体目录
    type-aliases-package: com.example.demo12.mybatis.entity
    configuration:
#        打印日志
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

